### ISSUE TITLE
신고 Entity들의 build-fail 문제

### ISSUE THREAD

**Issue by VINTO1819** [Software-Meister-High-School-Community/MOIZA-Spring-Server#50]
##### **📘 Summary**

- issue #16 에서 발생한 문법오류입니다
- FeedReport랑 UserReport에서 build fail을 확인했습니다
- BaseTimeEntity의 int형 `getId()` getter와, 자식 클래스의 FeedReportId, UserReportId 타입의 `getId()` 메소드가 충돌이 일어난 거 같습니다. (부모 메소드와 오버라이드하는 메소드의 리턴타입이 달라서 충돌났다는 뜻)

------

##### **⭐ Code Contents**

- [x] FeedReport.java
- [x] UserReport.java

------

##### **📜 Please refer to it's**

* Id의 getter 메소드 타입충돌로 일어난 문제니까, BaseTimeIdEntity 말고 BaseTimeEntity로 바꾸면 될거 같습니다
------

**Comment by softpeanut** [comment]
제가 왜 그런지 모르겠는데 각각의 FeedReport와 UserReport, CommentReport에는 시간 컬럼이 erd에 없는 것 같네요. 추상클래스 상속을 모두 없애면 될 것 같아요

**Comment by VINTO1819** [comment]
그러면 추상클래스 상속은 없애도록 하겠습니다
